TARGET = firmware
BUILD_DIR = build
ST_FREQ = 950

# Which demo in examples/ provides main(). Override on the command line,
# e.g. `make DEMO=usb_demo` or `make DEMO=usb_demo flash`.
DEMO ?= mips_console_demo

CC      = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
SIZE    = arm-none-eabi-size

ifeq ($(wildcard examples/$(DEMO).c),)
$(error Unknown DEMO "$(DEMO)". Available demos: $(patsubst examples/%.c,%,$(wildcard examples/*.c)))
endif

MCUFLAGS = \
-mcpu=cortex-m4 \
-mthumb

CFLAGS = \
$(MCUFLAGS) \
-MMD -MP \
-O0 \
-g3 \
-Wall \
-ffunction-sections \
-fdata-sections \
-DSTM32L432xx \
-Ivendor/CMSIS/CMSIS/Core/Include \
-Ivendor/STM32L4_Device/Include \
-Isrc \
-Isrc/usb \
-Isrc/console_commands

LDFLAGS = \
-Tlinker/STM32L432KC_FLASH.ld \
-Wl,--gc-sections \
-Wl,-Map=$(BUILD_DIR)/$(TARGET).map \
-specs=nano.specs

SRC_C := $(wildcard src/*.c)
SRC_C += $(wildcard src/usb/*.c)
SRC_C += $(wildcard src/console_commands/*.c)
SRC_C += vendor/STM32L4_Device/Source/Templates/system_stm32l4xx.c
SRC_C += examples/$(DEMO).c

SRC_S := startup/startup_stm32l432xx.s

OBJ_C := $(patsubst %.c,$(BUILD_DIR)/%.o,$(SRC_C))
OBJ_S := $(patsubst %.s,$(BUILD_DIR)/%.o,$(SRC_S))

OBJ := $(OBJ_C) $(OBJ_S)

ELF = $(BUILD_DIR)/$(TARGET).elf
BIN = $(BUILD_DIR)/$(TARGET).bin

# Switching DEMO changes nothing make can see: every object file is already
# built and older than the ELF, so make would report "Nothing to be done" and
# `flash` would push the PREVIOUS demo to the board. This stamp only exists for
# the DEMO currently selected, so changing DEMO forces a relink.
DEMO_STAMP = $(BUILD_DIR)/.demo-$(DEMO)

all: $(ELF)

$(DEMO_STAMP):
	@mkdir -p $(dir $@)
	@rm -f $(BUILD_DIR)/.demo-*
	@touch $@

$(ELF): $(OBJ) $(DEMO_STAMP)
	@mkdir -p $(dir $@)
	$(CC) $(OBJ) $(MCUFLAGS) $(LDFLAGS) -o $@
	$(SIZE) $@

$(BIN): $(ELF)
	$(OBJCOPY) -O binary $< $@

$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/%.o: %.s
	@mkdir -p $(dir $@)
	$(CC) $(MCUFLAGS) -c $< -o $@

# src/mips_full_test.h is generated from the MIPS assembly and is committed, so a
# normal firmware build needs no MIPS toolchain. This rule only fires when the
# assembly is actually newer, and then clang regenerates the header -- which the
# -MMD dependency files turn into a rebuild of src/mips_programs.c and a relink.
# Adding another program means adding its header here too.
src/mips_full_test.h: mips_assembly_test/full_test.S mips_assembly_test/isa.inc
	$(MAKE) -C mips_assembly_test

flash: $(BIN)
	st-flash --freq $(ST_FREQ) --reset --connect-under-reset write $(BIN) 0x08000000

list-demos:
	@echo "Available demos (make DEMO=<name> ...):"
	@for f in examples/*.c; do echo "  $$(basename $$f .c)"; done

clean:
	rm -rf $(BUILD_DIR)
	$(MAKE) -C mips_assembly_test clean

# Generated by -MMD: tells make which headers each object really depends on.
# Without this, editing any header leaves stale objects behind.
-include $(OBJ:.o=.d)

.PHONY: all flash clean list-demos